require "user.options"
require "user.keymaps"
require "user.lazy"
require "user.colorscheme"
require "user.cmp"
require "user.lsp"
require "user.telescope"
require "user.treesitter"
-- require "user.autopairs"
-- require "user.comment"
require "user.gitsigns"
require "user.nvim-tree"
require "user.bufferline"
require "user.lualine"
require "user.toggleterm"
require "user.symbols-outline"
require "user.fugitive"
require "user.which-key"
require "user.null-ls"
require "user.telescope-tabs"
